; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; platformio.ini
; Edge-Based Context-Aware Precision Irrigation System
; PlatformIO Project Configuration

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor settings
monitor_speed = 115200

;automatically decodes ESP32 crash logs (crucial for debugging)
monitor_filters = esp32_exception_decoder

; Build options, enables debugging with colors
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_COLORS=1

; Partition scheme for more app space (needed for ML model)
board_build.partitions = default.csv

; Library dependencies, PlatformIO will auto-download these libraries. No manual library hunting.
lib_deps =
    ; DHT22 sensor
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    ; BH1750 light sensor
    claws/BH1750 @ ^1.3.0
    ; SD card
    arduino-libraries/SD @ ^1.2.4
    ; Real-time clock (for timestamps)
    adafruit/RTClib @ ^2.1.3

; Upload options
upload_speed = 921600

; Debugging
debug_tool = esp-prog

